[package]
name = "typinator"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
rand = "0.9.0"
lazy_static = "1.5.0"
futures = "0.3.31"
futures-timer = "3.0.3"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
